import {
  PassengerUser,
  StaffUser,
  TripData,
  InternalTicketRecord,
  PassengerManifestItem,
  OperatorProfileData,
  TransitRoute,
  Vehicle,
  NearbyService,
  SavedPlace,
  RecentSearch,
  TerminalStatus,
} from '../types/index.js';

export const SEED_PASSENGERS: PassengerUser[] = [
  {
    id: 'usr-sara-01',
    name: 'Sara Miller',
    email: 'sara.miller@gmail.com',
    phone: '+1 (555) 234-8901',
    role: 'PASSENGER',
    concessionType: 'STANDARD_ADULT',
    metroPayBalance: 42.5,
    digitalTicketsCount: 3,
    emailVerified: true,
    createdAt: '2024-01-15T08:00:00.000Z',
    lastLoginAt: '2026-10-08T05:00:00.000Z',
    status: 'ACTIVE',
    savedRoutesCount: 4,
  },
  {
    id: 'usr-john-02',
    name: 'John Smith',
    email: 'john.smith@gmail.com',
    phone: '+1 (555) 876-5432',
    role: 'PASSENGER',
    concessionType: 'STUDENT_YOUTH',
    metroPayBalance: 18.0,
    digitalTicketsCount: 1,
    emailVerified: true,
    createdAt: '2024-02-10T11:20:00.000Z',
    lastLoginAt: '2026-10-07T14:30:00.000Z',
    status: 'ACTIVE',
    savedRoutesCount: 2,
  },
  {
    id: 'usr-priya-03',
    name: 'Priya Patel',
    email: 'priya.patel@transitpulse.lk',
    phone: '+94 77 123 4567',
    role: 'PASSENGER',
    concessionType: 'STANDARD_ADULT',
    metroPayBalance: 75.0,
    digitalTicketsCount: 5,
    emailVerified: true,
    createdAt: '2024-03-01T09:15:00.000Z',
    lastLoginAt: '2026-10-08T04:10:00.000Z',
    status: 'ACTIVE',
    savedRoutesCount: 6,
  },
];

export const SEED_STAFF: StaffUser[] = [
  {
    id: 'stf-drv-84920',
    staffId: 'DRV-84920',
    name: 'Kavithusan',
    email: 'DRV-84920@transitpulse.gov',
    role: 'DRIVER',
    status: 'ACTIVE',
    terminalAccess: true,
    vehicleAccess: ['Bus #4028', 'Bus #4208', 'Bus #4105'],
    assignedVehicle: 'Bus #4028',
    nfcBadgeId: 'MTA-NFC-8492-SEC',
    dispatchZone: 'DISPATCH ZONE 4',
    badgeLabel: 'Senior Conductor / Operator',
    shiftHours: '06:00 - 15:30',
    createdAt: '2023-04-12T00:00:00.000Z',
    updatedAt: '2026-10-08T00:00:00.000Z',
    failedAttempts: 0,
  },
  {
    id: 'stf-drv-kavi-02',
    staffId: 'DRV-77102',
    name: 'M. Kavi',
    email: 'm.kavi@transitpulse.gov',
    role: 'DRIVER',
    status: 'ACTIVE',
    terminalAccess: true,
    vehicleAccess: ['Bus #4028'],
    assignedVehicle: 'Bus #4028',
    nfcBadgeId: 'MTA-NFC-7710-SEC',
    dispatchZone: 'DISPATCH ZONE 4',
    badgeLabel: 'Transit Operator',
    createdAt: '2023-06-18T00:00:00.000Z',
    updatedAt: '2026-10-08T00:00:00.000Z',
    failedAttempts: 0,
  },
  {
    id: 'stf-dsp-04',
    staffId: 'DSP-99014',
    name: 'Zone 4 Controller',
    email: 'dispatch.z4@transitpulse.gov',
    role: 'DISPATCHER',
    status: 'ACTIVE',
    terminalAccess: true,
    vehicleAccess: ['ALL'],
    assignedVehicle: 'CONTROL-Z4',
    dispatchZone: 'DISPATCH ZONE 4',
    badgeLabel: 'Regional Dispatch Officer',
    createdAt: '2022-09-01T00:00:00.000Z',
    updatedAt: '2026-10-08T00:00:00.000Z',
    failedAttempts: 0,
  },
  {
    id: 'stf-ins-09',
    staffId: 'INS-44120',
    name: 'S. Roy',
    email: 'inspector.roy@transitpulse.gov',
    role: 'ADMIN',
    status: 'ACTIVE',
    terminalAccess: true,
    vehicleAccess: ['ALL'],
    assignedVehicle: 'INSPECT-01',
    dispatchZone: 'DISPATCH ZONE 4',
    badgeLabel: 'Chief Fare Compliance Inspector',
    createdAt: '2021-11-20T00:00:00.000Z',
    updatedAt: '2026-10-08T00:00:00.000Z',
    failedAttempts: 0,
  },
];

export const INITIAL_TRIP: TripData = {
  id: 'TRIP-4028-0941',
  busNumber: 'Bus #4028',
  driverName: 'Mr. Kavithusan',
  conductorName: 'Conductor S. Perera',
  routeNumber: 'LINE 42',
  routeName: 'Downtown - Univ Express',
  origin: 'Market Square',
  destination: 'Tech Campus',
  zone: 'Zone A',
  tripStatus: 'ACTIVE',
  scheduleStatus: 'ON_TIME',
  currentStop: 'Market St & 4th',
  doorStatus: 'OPEN',
  nextStop: 'Terminal 6',
  etaMinutes: 6,
  occupiedSeats: 42,
  totalSeats: 55,
  digitalQrCount: 36,
  cashFareCount: 4,
  pendingFailCount: 2,
  shiftDigitalFareTotal: 2340,
  startedAt: '2026-10-08T05:00:00.000Z',
  recentActivity: [
    {
      id: 'act-001',
      ticketId: 'TK-9824',
      ticketTypeLabel: 'Standard Single',
      eventText: 'Ticket #TK-9824 (PASS)',
      result: 'PASS',
      timestamp: Date.now() - 120000,
      fareAmount: 65,
      method: 'QR',
      passengerName: 'K. Bandara',
    },
    {
      id: 'act-002',
      ticketId: 'TK-9810',
      ticketTypeLabel: 'Concession Pass',
      eventText: 'Ticket #TK-9810 (PASS)',
      result: 'PASS',
      timestamp: Date.now() - 240000,
      fareAmount: 35,
      method: 'NFC',
      passengerName: 'M. Fernando',
    },
    {
      id: 'act-003',
      ticketId: 'TK-9788',
      ticketTypeLabel: 'Day Pass',
      eventText: 'Ticket #TK-9788 (PASS)',
      result: 'PASS',
      timestamp: Date.now() - 360000,
      fareAmount: 150,
      method: 'QR',
      passengerName: 'T. Alwis',
    },
  ],
  stops: [
    {
      id: 'stp-01',
      name: 'Market St & 4th',
      distanceMeters: 0,
      etaMinutes: 0,
      scheduledTime: '08:15',
      isCompleted: true,
    },
    {
      id: 'stp-02',
      name: 'Malabe Center',
      distanceMeters: 1400,
      etaMinutes: 4,
      scheduledTime: '08:28',
      isCompleted: false,
    },
    {
      id: 'stp-03',
      name: 'Terminal 6',
      distanceMeters: 3100,
      etaMinutes: 6,
      scheduledTime: '08:42',
      isCompleted: false,
    },
    {
      id: 'stp-04',
      name: 'Tech Campus',
      distanceMeters: 5200,
      etaMinutes: 14,
      scheduledTime: '08:55',
      isCompleted: false,
    },
  ],
};

export const SEED_TICKETS: InternalTicketRecord[] = [
  {
    ticketId: 'TK-9021',
    type: 'Standard Single',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 65,
    status: 'VALID',
    passengerName: 'Dilshan Silva',
    expiresAt: Date.now() + 3600000,
    bookingReference: 'MTA-BK-90214',
    originStop: 'Market St & 4th',
    destinationStop: 'University Malabe Campus',
    originZone: 'Zone 1',
    destinationZone: 'Zone 2',
    paymentStatus: 'PAID',
    paymentMethod: 'Digital Wallet Pay',
    transactionId: 'TXN-884028-091',
    passengerCount: 1,
  },
  {
    ticketId: 'TK-9018',
    type: 'Concession Pass',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 35,
    status: 'VALID',
    passengerName: 'Kamal Perera',
    expiresAt: Date.now() + 7200000,
    bookingReference: 'MTA-BK-90180',
    originStop: '3rd & Pine',
    destinationStop: 'Malabe Center',
    originZone: 'Zone 1',
    destinationZone: 'Zone 2',
    paymentStatus: 'PAID',
    paymentMethod: 'Concession Transit Card',
    transactionId: 'TXN-884028-084',
    passengerCount: 1,
  },
  {
    ticketId: 'TK-9044',
    type: 'Standard Single',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 65,
    status: 'VALID',
    passengerName: 'Anura Fernando',
    expiresAt: Date.now() + 3600000,
    bookingReference: 'MTA-BK-90442',
    originStop: 'Market St & 4th',
    destinationStop: 'Univ. City Terminal',
    originZone: 'Zone 1',
    destinationZone: 'Zone 3',
    paymentStatus: 'PAID',
    paymentMethod: 'Visa NFC Pass',
    transactionId: 'TXN-884028-072',
    passengerCount: 1,
  },
  {
    ticketId: 'TK-9055',
    type: 'Day Pass',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 150,
    status: 'VALID',
    passengerName: 'Nimal Jayawardena',
    expiresAt: Date.now() + 18000000,
    bookingReference: 'MTA-BK-90559',
    originStop: 'Downtown Terminal',
    destinationStop: 'Metro Outer Ring',
    originZone: 'Zone 1',
    destinationZone: 'Zone 4',
    paymentStatus: 'PAID',
    paymentMethod: 'MasterCard Contactless',
    transactionId: 'TXN-884028-066',
    passengerCount: 1,
  },
  {
    ticketId: 'TK-7740',
    type: 'Standard Single',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 65,
    status: 'USED',
    passengerName: 'Kasun Raj',
    expiresAt: Date.now() + 1800000,
    usedAt: Date.now() - 600000,
    bookingReference: 'MTA-BK-77401',
    originStop: 'Market Square',
    destinationStop: 'Tech Campus',
  },
  {
    ticketId: 'TK-8832',
    type: 'Standard Single',
    routeId: 'LINE 42',
    tripId: 'TRIP-4028-0941',
    fareAmount: 65,
    status: 'EXPIRED',
    passengerName: 'Chathura Wickrama',
    expiresAt: Date.now() - 7200000,
    bookingReference: 'MTA-BK-88325',
    originStop: 'Market Square',
    destinationStop: 'Tech Campus',
  },
  {
    ticketId: 'TK-4411',
    type: 'Standard Single',
    routeId: 'ROUTE 138',
    tripId: 'TRIP-138-001',
    fareAmount: 70,
    status: 'VALID',
    passengerName: 'Danushka Senanayake',
    expiresAt: Date.now() + 3600000,
    bookingReference: 'MTA-BK-44110',
    originStop: 'Pettah Terminal',
    destinationStop: 'Homagama',
  },
];

export const INITIAL_MANIFEST: PassengerManifestItem[] = [
  {
    id: 'mnf-01',
    ticketId: 'TK-9021',
    passengerName: 'Dilshan Silva',
    type: 'Standard Single',
    boardedAtStop: 'Market St & 4th',
    boardedAtTime: '08:16 AM',
    fare: 65,
    status: 'ONBOARD',
    method: 'QR',
    category: 'DIGITAL',
    validationStatus: 'VALID',
    destination: 'Tech Campus',
  },
  {
    id: 'mnf-02',
    ticketId: 'TK-9018',
    passengerName: 'Kamal Perera',
    type: 'Concession Pass',
    boardedAtStop: 'Market Square',
    boardedAtTime: '08:08 AM',
    fare: 35,
    status: 'ONBOARD',
    method: 'NFC',
    category: 'DIGITAL',
    validationStatus: 'VALID',
    destination: 'Malabe Center',
  },
  {
    id: 'mnf-03',
    ticketId: 'TK-9044',
    passengerName: 'Anura Fernando',
    type: 'Standard Single',
    boardedAtStop: 'Market St & 4th',
    boardedAtTime: '08:17 AM',
    fare: 65,
    status: 'ONBOARD',
    method: 'QR',
    category: 'DIGITAL',
    validationStatus: 'VALID',
    destination: 'Tech Campus',
  },
  {
    id: 'mnf-04',
    ticketId: 'TK-9055',
    passengerName: 'Nimal Jayawardena',
    type: 'Day Pass',
    boardedAtStop: 'Market Square',
    boardedAtTime: '08:05 AM',
    fare: 150,
    status: 'ONBOARD',
    method: 'NFC',
    category: 'DIGITAL',
    validationStatus: 'VALID',
    destination: 'Terminal 6',
  },
];

export const INITIAL_OPERATOR_PROFILE: OperatorProfileData = {
  staffId: 'DRV-84920',
  name: 'Kavithusan',
  role: 'Senior Conductor / Operator',
  depot: 'Div 4 Depot',
  rating: 4.95,
  ratingNote: 'Safe Driver Commendation',
  tier: 'Tier 1 Safe',
  dutyStatus: 'ON DUTY',
  activeRoute: 'Line 42',
  routeDescription: 'Downtown - Univ Express',
  assignedFleet: 'Bus #4028',
  fleetType: 'Electric Hybrid',
  shiftWindow: '06:00 - 15:30',
  shiftStartEpoch: Date.now() - 18720000,
  shiftEndEpoch: Date.now() + 15420000,
  terminalStart: '06:00 AM',
  estEodDepot: 'Div 4 Maintenance Bay',
  todaysBoardings: 438,
  boardingsTrendPct: 14.2,
  cashlessBoardingPct: 94.2,
  scansCompleted: 392,
  validPassesPct: 100,
  onTimeDeparturePct: 98.5,
  punctualityStatus: 'Tier-1 Punctuality',
  feedStatus: 'REAL-TIME TELEMETRY CONNECTED',
  certifications: [
    {
      id: 'cert-01',
      name: 'CDL Class B w/ Air Brakes',
      category: 'LICENSE',
      detail: 'Commercial License - Valid until Oct 2028',
      validUntil: '2028-10-31',
      status: 'VERIFIED',
    },
    {
      id: 'cert-02',
      name: 'Optical Validator FIPS-140 Token',
      category: 'SECURITY',
      detail: 'FIPS-140 Level 2 Key Token - Active',
      validUntil: '2026-12-31',
      status: 'ACTIVE',
    },
    {
      id: 'cert-03',
      name: 'Emergency First Aid & CPR',
      category: 'SAFETY',
      detail: 'MTA Public Safety Certified - Re-cert 2025',
      validUntil: '2027-04-15',
      status: 'VALID',
    },
  ],
  diagnostics: {
    airGapCachedTokens: 3240,
    airGapStatus: 'Synced',
    scannerName: 'POS-Scanner-99',
    scannerConnected: true,
    scannerBeepHaptics: true,
    brightnessBoost: true,
  },
};

export const SEED_ROUTES: TransitRoute[] = [
  {
    id: 'route-line-42',
    routeNumber: 'LINE 42',
    name: 'Downtown - Univ Express',
    type: 'bus',
    color: '#7C3AED',
    isStarred: true,
    coordinates: [
      { latitude: 6.9271, longitude: 79.8612 },
      { latitude: 6.9214, longitude: 79.8732 },
      { latitude: 6.9147, longitude: 79.8895 },
      { latitude: 6.9073, longitude: 79.9142 },
      { latitude: 6.9032, longitude: 79.9321 },
      { latitude: 6.9015, longitude: 79.9542 },
    ],
    stops: [
      {
        id: 'stp-01',
        name: 'Market St & 4th',
        coordinate: { latitude: 6.9271, longitude: 79.8612 },
        sequence: 1,
        status: 'completed',
        platform: 'Bay A',
      },
      {
        id: 'stp-02',
        name: 'Malabe Center',
        coordinate: { latitude: 6.9147, longitude: 79.8895 },
        sequence: 2,
        status: 'current',
        platform: 'Bay 2',
        isBoarding: true,
      },
      {
        id: 'stp-03',
        name: 'Terminal 6',
        coordinate: { latitude: 6.9073, longitude: 79.9142 },
        sequence: 3,
        status: 'upcoming',
        platform: 'Bay 4',
      },
      {
        id: 'stp-04',
        name: 'Tech Campus',
        coordinate: { latitude: 6.9015, longitude: 79.9542 },
        sequence: 4,
        status: 'upcoming',
        platform: 'Main Gate',
      },
    ],
  },
  {
    id: 'route-exp-8',
    routeNumber: 'EXPRESS 8',
    name: 'Harbor Gateway - Airport Fastlink',
    type: 'bus',
    color: '#2563EB',
    isStarred: false,
    coordinates: [
      { latitude: 6.9412, longitude: 79.8512 },
      { latitude: 7.0214, longitude: 79.8832 },
      { latitude: 7.1805, longitude: 79.8841 },
    ],
    stops: [
      {
        id: 'stp-e8-1',
        name: 'Harbor Gateway Station',
        coordinate: { latitude: 6.9412, longitude: 79.8512 },
        sequence: 1,
        status: 'upcoming',
      },
      {
        id: 'stp-e8-2',
        name: 'International Airport T1',
        coordinate: { latitude: 7.1805, longitude: 79.8841 },
        sequence: 2,
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'route-metro-blue',
    routeNumber: 'METRO BLUE',
    name: 'Coastal Highspeed Light Rail',
    type: 'train',
    color: '#059669',
    isStarred: true,
    coordinates: [
      { latitude: 6.935, longitude: 79.845 },
      { latitude: 6.892, longitude: 79.858 },
      { latitude: 6.845, longitude: 79.865 },
      { latitude: 6.801, longitude: 79.878 },
    ],
    stops: [
      {
        id: 'stp-mb-1',
        name: 'Fort Central Rail Station',
        coordinate: { latitude: 6.935, longitude: 79.845 },
        sequence: 1,
        status: 'completed',
        platform: 'Track 1',
      },
      {
        id: 'stp-mb-2',
        name: 'Kollupitiya Junction',
        coordinate: { latitude: 6.892, longitude: 79.858 },
        sequence: 2,
        status: 'upcoming',
        platform: 'Track 2',
      },
      {
        id: 'stp-mb-3',
        name: 'Mount Lavinia Coastal',
        coordinate: { latitude: 6.845, longitude: 79.865 },
        sequence: 3,
        status: 'upcoming',
        platform: 'Track 1',
      },
    ],
  },
  {
    id: 'route-jaffna-nallur',
    routeNumber: 'LINE 765',
    name: 'Jaffna - Nallur Express Link',
    type: 'bus',
    color: '#0284C7',
    isStarred: true,
    coordinates: [
      { latitude: 9.6615, longitude: 80.0145 },
      { latitude: 9.6655, longitude: 80.0185 },
      { latitude: 9.6698, longitude: 80.023 },
      { latitude: 9.6745, longitude: 80.0298 },
    ],
    stops: [
      {
        id: 'stp-jn-1',
        name: 'Jaffna Central Bus Stand',
        coordinate: { latitude: 9.6615, longitude: 80.0145 },
        sequence: 1,
        status: 'completed',
        platform: 'Bay 1',
      },
      {
        id: 'stp-jn-2',
        name: 'Teaching Hospital Junction',
        coordinate: { latitude: 9.6655, longitude: 80.0185 },
        sequence: 2,
        status: 'current',
        platform: 'Bay 2',
        isBoarding: true,
      },
      {
        id: 'stp-jn-3',
        name: 'Clock Tower Junction',
        coordinate: { latitude: 9.6698, longitude: 80.023 },
        sequence: 3,
        status: 'upcoming',
      },
      {
        id: 'stp-jn-4',
        name: 'Nallur Kandaswamy Kovil',
        coordinate: { latitude: 9.6745, longitude: 80.0298 },
        sequence: 4,
        status: 'upcoming',
        platform: 'Main Gate',
      },
    ],
  },
];

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'veh-bus-4028',
    vehicleNumber: 'Bus #4028',
    routeNumber: 'LINE 42',
    routeName: 'Downtown - Univ Express',
    type: 'bus',
    latitude: 6.9073,
    longitude: 79.9142,
    destination: 'Tech Campus',
    eta: 6,
    currentStop: 'Market St & 4th',
    nextStop: 'Terminal 6',
    occupancy: 'high',
    status: 'on-time',
    isStarred: true,
    speed: 38,
    heading: 95,
    platform: 'Bay A',
    vehicleSpec: 'Electric Hybrid',
    freeSeats: 13,
    targetStopName: 'Terminal 6',
    targetStopDistanceMeters: 450,
    delayMinutes: 0,
    stopsAway: 1,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'veh-bus-4208',
    vehicleNumber: 'Bus #4208',
    routeNumber: 'LINE 42',
    routeName: 'Downtown - Univ Express',
    type: 'bus',
    latitude: 6.9214,
    longitude: 79.8732,
    destination: 'Tech Campus',
    eta: 14,
    currentStop: 'Depot Div 4',
    nextStop: 'Market Square',
    occupancy: 'low',
    status: 'on-time',
    isStarred: false,
    speed: 42,
    heading: 110,
    vehicleSpec: 'Zero-Emission EV',
    freeSeats: 50,
    delayMinutes: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'veh-train-102',
    vehicleNumber: 'Train #T-102',
    routeNumber: 'METRO BLUE',
    routeName: 'Coastal Highspeed Light Rail',
    type: 'train',
    latitude: 6.892,
    longitude: 79.858,
    destination: 'Mount Lavinia',
    eta: 3,
    currentStop: 'Fort Central Rail Station',
    nextStop: 'Kollupitiya Junction',
    occupancy: 'medium',
    status: 'on-time',
    isStarred: true,
    speed: 68,
    heading: 180,
    platform: 'Track 1',
    vehicleSpec: 'EMU Rapid Rail',
    freeSeats: 124,
    delayMinutes: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'veh-bus-jaffna-765',
    vehicleNumber: 'Bus #NP-765',
    routeNumber: 'LINE 765',
    routeName: 'Jaffna - Nallur Express Link',
    type: 'bus',
    latitude: 9.6620,
    longitude: 80.0150,
    destination: 'Nallur',
    eta: 8,
    currentStop: 'Jaffna Central Bus Stand',
    nextStop: 'Teaching Hospital Junction',
    occupancy: 'medium',
    status: 'arriving',
    isStarred: true,
    speed: 32,
    heading: 45,
    platform: 'Bay 1',
    vehicleSpec: 'CTB Express Coach',
    freeSeats: 22,
    targetStopName: 'Nallur Kandaswamy Kovil',
    targetStopDistanceMeters: 1800,
    delayMinutes: 0,
    stopsAway: 2,
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_NEARBY_SERVICES: NearbyService[] = [
  {
    id: 'srv-jaffna-01',
    vehicleId: 'veh-bus-jaffna-765',
    routeId: 'route-jaffna-nallur',
    routeNumber: 'LINE 765',
    serviceType: 'bus',
    serviceName: 'Jaffna - Nallur Express',
    destination: 'Nallur',
    distance: 180,
    eta: 8,
    platform: 'Bay 1',
    occupancy: 'medium',
    status: 'arriving',
    isStarred: true,
  },
  {
    id: 'srv-01',
    vehicleId: 'veh-bus-4028',
    routeId: 'route-line-42',
    routeNumber: 'LINE 42',
    serviceType: 'bus',
    serviceName: 'Downtown - Univ Express',
    destination: 'Tech Campus',
    distance: 120,
    eta: 2,
    platform: 'Bay 1',
    occupancy: 'high',
    status: 'arriving',
    isStarred: true,
  },
  {
    id: 'srv-02',
    vehicleId: 'veh-train-102',
    routeId: 'route-metro-blue',
    routeNumber: 'METRO BLUE',
    serviceType: 'train',
    serviceName: 'Coastal Highspeed Rail',
    destination: 'Mount Lavinia',
    distance: 450,
    eta: 5,
    platform: 'Track 2',
    occupancy: 'medium',
    status: 'on-time',
    isStarred: true,
  },
  {
    id: 'srv-03',
    routeId: 'route-exp-8',
    routeNumber: 'EXPRESS 8',
    serviceType: 'bus',
    serviceName: 'Airport Fastlink',
    destination: 'International Airport',
    distance: 820,
    eta: 9,
    platform: 'Bay 4',
    occupancy: 'low',
    status: 'on-time',
    isStarred: false,
  },
];

export const SEED_SAVED_PLACES: SavedPlace[] = [
  {
    id: 'plc-01',
    name: 'Home',
    address: '42 Orchid Gardens, Colombo 07',
    latitude: 6.902,
    longitude: 79.871,
    type: 'home',
  },
  {
    id: 'plc-02',
    name: 'University Campus',
    address: 'SLIIT New Malabe Campus, Kaduwela Rd',
    latitude: 6.9015,
    longitude: 79.9542,
    type: 'school',
  },
  {
    id: 'plc-03',
    name: 'Metro Work Hub',
    address: 'World Trade Center, Echelon Square',
    latitude: 6.933,
    longitude: 79.843,
    type: 'work',
  },
  {
    id: 'plc-04',
    name: 'Jaffna Central Bus Stand',
    address: 'Hospital Road, Jaffna Central',
    latitude: 9.6615,
    longitude: 80.0145,
    type: 'station',
  },
  {
    id: 'plc-05',
    name: 'Nallur Kandaswamy Kovil',
    address: 'Point Pedro Road, Nallur, Jaffna',
    latitude: 9.6745,
    longitude: 80.0298,
    type: 'favorite',
  },
];

export const SEED_RECENT_SEARCHES: RecentSearch[] = [
  {
    id: 'srch-00',
    query: 'Jaffna to Nallur Express',
    timestamp: new Date().toISOString(),
    type: 'route',
    targetId: 'route-jaffna-nallur',
  },
  {
    id: 'srch-01',
    query: 'Line 42 Downtown',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    type: 'route',
    targetId: 'route-line-42',
  },
  {
    id: 'srch-02',
    query: 'Nallur Kandaswamy Kovil',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    type: 'place',
  },
];

export const INITIAL_TERMINAL_STATUS: TerminalStatus = {
  terminalId: 'TERM-4028-V4',
  vehicleId: 'veh-bus-4028',
  vehicleNumber: 'Bus #4028',
  transitAuthority: 'Metro Transit Authority (MTA)',
  dispatchZone: 'DISPATCH ZONE 4',
  terminalState: 'READY',
  version: 'v4.8.2-ops',
  connectionStatus: 'CONNECTED',
  gpsLock: true,
  pingMs: 18,
  lastHeartbeat: new Date().toISOString(),
};
